app:
  name: testName
  description: ${app.name} test description
list.values: One, Two, Three
db_map.values: "{connectionString: 'test', userName: 'foo', password: 'pass'}"

# @ConfigurationProperties annotated Configuration class will look up props starting with 'db'
db:
  connection: "{connectionstring:'test', userName:'foo', password:'pass'}"
  host: 127.0.0.1
  port: 4800